" Activate mouse usage
set mouse=a

" -------------------------------------------------------------------------------
" Highlight sources
syntax on
" For more colorshemes run 'ls /usr/share/vim/vim*/colors | grep .vim'
colorscheme desert 

" -------------------------------------------------------------------------------
" Display lines number
set number

" 
set clipboard=unnamedplus
"set guioptions+=a

" -------------------------------------------------------------------------------
" Matching Parenthesis
hi MatchParen cterm=bold ctermbg=red ctermfg=green

" -------------------------------------------------------------------------------
" Search 
set hlsearch
set incsearch 			" Display search while typing 
set ic 				    " Ignore case for search, use :set noic to undo
hi Search ctermbg=LightYellow
hi Search ctermfg=Red	

" -------------------------------------------------------------------------------
" For clipboard
map <C-y> :w !xclip -sel c <CR><CR>

" -------------------------------------------------------------------------------
" Tabs
set tabstop=4       " Set tab width to 4 spaces
set shiftwidth=4    " Set indentation width to 4 spaces
set expandtab       " Use spaces instead of tabs

" -------------------------------------------------------------------------------
" Source vimrc of a project folder when you run vim .
" set exrc

set cursorline      " Highlight the current line
" -------------------------------------------------------------------------------
" Will not wrap very long lines of text
set nowrap

" 
" set hidden


" -------------------------------------------------------------------------------
set scrolloff=10 " Cursor more in the middle while scrolling


" -------------------------------------------------------------------------------
set signcolumn=yes

" 
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey







