#!/bin/bash

# This script will detect all subdirectories in `~/Documents/Appimages` directory
# and for each subdirectory will create a .desktop entry in `/usr/share/applications/`
# The name of the .desktop file will be the same as the dir name. Moreover, inside 
# each dir you can have .AppImage files, the script will detect the newest 
# verion and will include it in the .desktop file. Along with the .AppImage you 
# can also have an icon either as .png or .jpg which will also be included

CLR_RED='\033[0;31m'
CLR_GREEN='\033[0;32m'
CLR_YELLOW='\033[0;33m'
CLR_RST='\033[0m'

# DEBUG prints
function echo_r(){ echo -e "${CLR_RED}$*${CLR_RST}"; }
function echo_g(){ echo -e "${CLR_GREEN}$*${CLR_RST}"; }
function echo_y(){ echo -e "${CLR_YELLOW}$*${CLR_RST}"; }

# Require root privileges to write to /usr/share/applications
if [[ $EUID -ne 0 ]]; then
  echo "Please run as root."
  exit 1
fi

BASE_DIR="~/Documents/Appimages"
DESKTOP_DIR="/usr/share/applications"

# Loop through each subdirectory
for dir in "$BASE_DIR"/*/; do
  [ -d "$dir" ] || continue

  app_name="$(basename "$dir")"
  app_dir="${BASE_DIR}/${app_name}"

  # Find the newest AppImage file
  app_exec=$(find "$app_dir" -type f -iname "*.AppImage" -printf "%T@ %p\n" 2>/dev/null | sort -nr | head -n1 | cut -d' ' -f2-)

  # Find an image for the icon (any extension)
  app_icon=$(find "$app_dir" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.svg" \) | head -n1)

  # If there is not an AppImage, then continue
  if [[ -z "$app_exec" ]]; then
    continue
  fi

  # .desktop file
  desktop_file="${DESKTOP_DIR}/${app_name}.desktop"

  # Log messages
  echo_y "[${app_name}] detected: "
  echo "    + Desktop entry path: ${desktop_file}"
  echo "    + Exec: ${app_exec}"
  echo "    + Name: ${app_name}"
  echo "    + Icon: ${app_icon}"
  echo "    Create Desktop enrty..."

  # If .desktop file already exists
  if [[ -f "$desktop_file" ]]; then
    if ! grep -Fxq '# [GENERATE_DESKTOP_ENTRIES_AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_LINE]' "$desktop_file"; then
      echo_r "    Desktop entry already exists and it is not generated by this script. Skipping..."
      echo
      continue
    fi
  fi  

  cat > "$desktop_file" <<EOF
[Desktop Entry]
# [GENERATE_DESKTOP_ENTRIES_AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_LINE]
# This file should be placed in '${desktop_file}'
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=${app_exec}
Name=${app_name}
Icon=${app_icon}
EOF

  # Make sure that .AppImage is executable
  sudo chmod +x ${app_exec}

  echo_g "    DONE!"
  echo
done

